#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  clang_executable = "/usr/bin/clang"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"


#[[layers]]
#  name = "debug"

[[layers]]
name = "format"

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]

[[layers]]
name = "format"

[[layers]]
  name = "checkers"
#show_cursor_error = false

  [options]
  enable_neomake = false
  enable_ale = true

[[custom_plugins]]
repo = 'itchyny/vim-cursorword'
#on_cmd = ["ColorHighlight", "ColorToggle"]
    merged = false

#[[custom_plugins]]
#repo = 'iamcco/markdown-preview.nvim'
#on_cmd = ["ColorHighlight", "ColorToggle"]
#    merged = false

#[[custom_plugins]]
#repo = 'plasticboy/vim-markdown'
#on_cmd = ["ColorHighlight", "ColorToggle"]
#    merged = false

